//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSlozka.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSlozka.Web.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginEmailInputLabel {
            get {
                return ResourceManager.GetString("LoginEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter.novotny@outlook.com.
        /// </summary>
        internal static string LoginEmailInputPlaceholder {
            get {
                return ResourceManager.GetString("LoginEmailInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginLoginButtonText {
            get {
                return ResourceManager.GetString("LoginLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string LoginPasswordInputAdornmentArialLabel {
            get {
                return ResourceManager.GetString("LoginPasswordInputAdornmentArialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPasswordInputLabel {
            get {
                return ResourceManager.GetString("LoginPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginRegisterButtonText {
            get {
                return ResourceManager.GetString("LoginRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESLOZKA.
        /// </summary>
        internal static string MainLayoutAppbarBrand {
            get {
                return ResourceManager.GetString("MainLayoutAppbarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string MainLayoutAppbarDrawerLinkAccount {
            get {
                return ResourceManager.GetString("MainLayoutAppbarDrawerLinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string MainLayoutAppbarDrawerLinkLogout {
            get {
                return ResourceManager.GetString("MainLayoutAppbarDrawerLinkLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainLayoutAppbarDrawerLinkSettings {
            get {
                return ResourceManager.GetString("MainLayoutAppbarDrawerLinkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkAboutApplication {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkAboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkAccount {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkBookmarks {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkDeleted {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkFiles {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkHistory {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkLogout {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkLogs {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage selectors.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageCodeLists {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageCodeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage repository.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageRepository {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageStatistics {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage tasks.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageTasks {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageUsers {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkNotifications {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkSettings {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkSharedWithMe {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterEmailInputLabel {
            get {
                return ResourceManager.GetString("RegisterEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter.novotny@outlook.com.
        /// </summary>
        internal static string RegisterEmailInputPlaceholder {
            get {
                return ResourceManager.GetString("RegisterEmailInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        internal static string RegisterFamilyNameInputLabel {
            get {
                return ResourceManager.GetString("RegisterFamilyNameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novotny.
        /// </summary>
        internal static string RegisterFamilyNameInputPlaceholder {
            get {
                return ResourceManager.GetString("RegisterFamilyNameInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        internal static string RegisterGivenNameInputLabel {
            get {
                return ResourceManager.GetString("RegisterGivenNameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter.
        /// </summary>
        internal static string RegisterGivenNameInputPlaceholder {
            get {
                return ResourceManager.GetString("RegisterGivenNameInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string RegisterLoginButtonText {
            get {
                return ResourceManager.GetString("RegisterLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string RegisterPasswordInputAdornmentAriaLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordInputAdornmentAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterPasswordInputLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password repeat.
        /// </summary>
        internal static string RegisterPasswordRepeatInputAdornmentAriaLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordRepeatInputAdornmentAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password repeat.
        /// </summary>
        internal static string RegisterPasswordRepeatInputLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordRepeatInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterRegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Email&apos; has invalid format..
        /// </summary>
        internal static string ValidationUserEmailFormat {
            get {
                return ResourceManager.GetString("ValidationUserEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Email&apos; has maximum length of 256 characters..
        /// </summary>
        internal static string ValidationUserEmailMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserEmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Email&apos; is required..
        /// </summary>
        internal static string ValidationUserEmailRequired {
            get {
                return ResourceManager.GetString("ValidationUserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Family name&apos; has maximum length of 256 characters..
        /// </summary>
        internal static string ValidationUserFamilyNameMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserFamilyNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Family name&apos; is required..
        /// </summary>
        internal static string ValidationUserFamilyNameRequired {
            get {
                return ResourceManager.GetString("ValidationUserFamilyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Given name&apos; has maximum length of 256 characters..
        /// </summary>
        internal static string ValidationUserGivenNameMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserGivenNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Given name&apos; is required..
        /// </summary>
        internal static string ValidationUserGivenNameRequired {
            get {
                return ResourceManager.GetString("ValidationUserGivenNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password&apos; must contain at least one lower case character..
        /// </summary>
        internal static string ValidationUserPasswordLowerCaseCharacter {
            get {
                return ResourceManager.GetString("ValidationUserPasswordLowerCaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password&apos; has maximum length of 256 characters..
        /// </summary>
        internal static string ValidationUserPasswordMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password&apos; has minimum length of 8 characters..
        /// </summary>
        internal static string ValidationUserPasswordMinLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password&apos; must contain at least one numberic character..
        /// </summary>
        internal static string ValidationUserPasswordNumericCharacter {
            get {
                return ResourceManager.GetString("ValidationUserPasswordNumericCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password&apos; must match the field &apos;Password repeat&apos;..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionMatch {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password repeat&apos; has maximum length of 256 characters..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password repeat&apos; has maximum length of 256 characters..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionMinLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password repetition&apos; is required..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionRequired {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password&apos; is required..
        /// </summary>
        internal static string ValidationUserPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password&apos; must contain at least one special character..
        /// </summary>
        internal static string ValidationUserPasswordSpecialCharacter {
            get {
                return ResourceManager.GetString("ValidationUserPasswordSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Password&apos; must contain at least one upper case character..
        /// </summary>
        internal static string ValidationUserPasswordUpperCaseCharacter {
            get {
                return ResourceManager.GetString("ValidationUserPasswordUpperCaseCharacter", resourceCulture);
            }
        }
    }
}
