//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSlozka.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSlozka.Web.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginFormEmailInputLabel {
            get {
                return ResourceManager.GetString("LoginFormEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string LoginFormEmailInputPasswordRequiredError {
            get {
                return ResourceManager.GetString("LoginFormEmailInputPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginFormLoginButton {
            get {
                return ResourceManager.GetString("LoginFormLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginFormPasswordInputLabel {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string LoginFormPasswordInputPasswordRequiredError {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string LoginFormPasswordInputShowPasswordAriaLabel {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputShowPasswordAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginFormRegisterButton {
            get {
                return ResourceManager.GetString("LoginFormRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutFormLogoutButton {
            get {
                return ResourceManager.GetString("LogoutFormLogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainLayoutAboutApplication {
            get {
                return ResourceManager.GetString("MainLayoutAboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string MainLayoutAccount {
            get {
                return ResourceManager.GetString("MainLayoutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boomarks.
        /// </summary>
        internal static string MainLayoutBookmarks {
            get {
                return ResourceManager.GetString("MainLayoutBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string MainLayoutDeleted {
            get {
                return ResourceManager.GetString("MainLayoutDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string MainLayoutFiles {
            get {
                return ResourceManager.GetString("MainLayoutFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string MainLayoutHistory {
            get {
                return ResourceManager.GetString("MainLayoutHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MainLayoutLogout {
            get {
                return ResourceManager.GetString("MainLayoutLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string MainLayoutLogs {
            get {
                return ResourceManager.GetString("MainLayoutLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage code lists.
        /// </summary>
        internal static string MainLayoutManageCodeLists {
            get {
                return ResourceManager.GetString("MainLayoutManageCodeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage disk space.
        /// </summary>
        internal static string MainLayoutManageRepository {
            get {
                return ResourceManager.GetString("MainLayoutManageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage task.
        /// </summary>
        internal static string MainLayoutManageTasks {
            get {
                return ResourceManager.GetString("MainLayoutManageTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string MainLayoutManageUsers {
            get {
                return ResourceManager.GetString("MainLayoutManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MainLayoutNotifications {
            get {
                return ResourceManager.GetString("MainLayoutNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainLayoutSettings {
            get {
                return ResourceManager.GetString("MainLayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        internal static string MainLayoutSharedWithMe {
            get {
                return ResourceManager.GetString("MainLayoutSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string MainLayoutStatistics {
            get {
                return ResourceManager.GetString("MainLayoutStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterFormEmailInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string RegisterFormEmailInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormEmailInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        internal static string RegisterFormFamilyNameInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormFamilyNameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string RegisterFormFamilyNameInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormFamilyNameInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        internal static string RegisterFormGivenNameInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormGivenNameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string RegisterFormGivenNameInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormGivenNameInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string RegisterFormLoginButton {
            get {
                return ResourceManager.GetString("RegisterFormLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterFormPasswordInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string RegisterFormPasswordInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormPasswordInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string RegisterFormPasswordInputShowPasswordAriaLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordInputShowPasswordAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password repeat.
        /// </summary>
        internal static string RegisterFormPasswordRepeatInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordRepeatInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string RegisterFormPasswordRepeatInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormPasswordRepeatInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string RegisterFormPasswordRepeatInputShowPasswordAriaLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordRepeatInputShowPasswordAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterFormRegisterButton {
            get {
                return ResourceManager.GetString("RegisterFormRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterFormTitle {
            get {
                return ResourceManager.GetString("RegisterFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has invalid format..
        /// </summary>
        internal static string ValidationUserEmailInvalidFormat {
            get {
                return ResourceManager.GetString("ValidationUserEmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be at most 256 characters long..
        /// </summary>
        internal static string ValidationUserEmailMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserEmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or passoword..
        /// </summary>
        internal static string ValidationUserEmailOrPasswordInvalid {
            get {
                return ResourceManager.GetString("ValidationUserEmailOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string ValidationUserEmailRequired {
            get {
                return ResourceManager.GetString("ValidationUserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name must be at most 256 characters long..
        /// </summary>
        internal static string ValidationUserFamilyNameMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserFamilyNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string ValidationUserFamilyNameRequired {
            get {
                return ResourceManager.GetString("ValidationUserFamilyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name must be at most 256 characters long..
        /// </summary>
        internal static string ValidationUserGivenNameMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserGivenNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string ValidationUserGivenNameRequired {
            get {
                return ResourceManager.GetString("ValidationUserGivenNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at most 256 characters long..
        /// </summary>
        internal static string ValidationUserPasswordMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and its repetion must match..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionDoesNotMatch {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password repetition must be at most 256 characters long..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionRequired {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string ValidationUserPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRequired", resourceCulture);
            }
        }
    }
}
