//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSlozka.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSlozka.Web.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginFormEmailInputLabel {
            get {
                return ResourceManager.GetString("LoginFormEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string LoginFormEmailInputPasswordRequiredError {
            get {
                return ResourceManager.GetString("LoginFormEmailInputPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginFormLoginButton {
            get {
                return ResourceManager.GetString("LoginFormLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginFormPasswordInputLabel {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string LoginFormPasswordInputPasswordRequiredError {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string LoginFormPasswordInputShowPasswordAriaLabel {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputShowPasswordAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginFormRegisterButton {
            get {
                return ResourceManager.GetString("LoginFormRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainLayoutAboutApplication {
            get {
                return ResourceManager.GetString("MainLayoutAboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string MainLayoutAccount {
            get {
                return ResourceManager.GetString("MainLayoutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boomarks.
        /// </summary>
        internal static string MainLayoutBookmarks {
            get {
                return ResourceManager.GetString("MainLayoutBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string MainLayoutDeleted {
            get {
                return ResourceManager.GetString("MainLayoutDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string MainLayoutFiles {
            get {
                return ResourceManager.GetString("MainLayoutFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string MainLayoutHistory {
            get {
                return ResourceManager.GetString("MainLayoutHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MainLayoutLogout {
            get {
                return ResourceManager.GetString("MainLayoutLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string MainLayoutLogs {
            get {
                return ResourceManager.GetString("MainLayoutLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage code lists.
        /// </summary>
        internal static string MainLayoutManageCodeLists {
            get {
                return ResourceManager.GetString("MainLayoutManageCodeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage disk space.
        /// </summary>
        internal static string MainLayoutManageRepository {
            get {
                return ResourceManager.GetString("MainLayoutManageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage task.
        /// </summary>
        internal static string MainLayoutManageTasks {
            get {
                return ResourceManager.GetString("MainLayoutManageTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string MainLayoutManageUsers {
            get {
                return ResourceManager.GetString("MainLayoutManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MainLayoutNotifications {
            get {
                return ResourceManager.GetString("MainLayoutNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainLayoutSettings {
            get {
                return ResourceManager.GetString("MainLayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        internal static string MainLayoutSharedWithMe {
            get {
                return ResourceManager.GetString("MainLayoutSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string MainLayoutStatistics {
            get {
                return ResourceManager.GetString("MainLayoutStatistics", resourceCulture);
            }
        }
    }
}
