//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSlozka.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSlozka.Web.Resources.App.cs", typeof(App_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailová adresa.
        /// </summary>
        internal static string LoginFormEmailInputLabel {
            get {
                return ResourceManager.GetString("LoginFormEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinné pole..
        /// </summary>
        internal static string LoginFormEmailInputPasswordRequiredError {
            get {
                return ResourceManager.GetString("LoginFormEmailInputPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        internal static string LoginFormLoginButton {
            get {
                return ResourceManager.GetString("LoginFormLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string LoginFormPasswordInputLabel {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinné pole..
        /// </summary>
        internal static string LoginFormPasswordInputPasswordRequiredError {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit heslo.
        /// </summary>
        internal static string LoginFormPasswordInputShowPasswordAriaLabel {
            get {
                return ResourceManager.GetString("LoginFormPasswordInputShowPasswordAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat se.
        /// </summary>
        internal static string LoginFormRegisterButton {
            get {
                return ResourceManager.GetString("LoginFormRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        internal static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string MainLayoutAboutApplication {
            get {
                return ResourceManager.GetString("MainLayoutAboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet.
        /// </summary>
        internal static string MainLayoutAccount {
            get {
                return ResourceManager.GetString("MainLayoutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záložky.
        /// </summary>
        internal static string MainLayoutBookmarks {
            get {
                return ResourceManager.GetString("MainLayoutBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazané.
        /// </summary>
        internal static string MainLayoutDeleted {
            get {
                return ResourceManager.GetString("MainLayoutDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory.
        /// </summary>
        internal static string MainLayoutFiles {
            get {
                return ResourceManager.GetString("MainLayoutFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historie.
        /// </summary>
        internal static string MainLayoutHistory {
            get {
                return ResourceManager.GetString("MainLayoutHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        internal static string MainLayoutLogout {
            get {
                return ResourceManager.GetString("MainLayoutLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logy.
        /// </summary>
        internal static string MainLayoutLogs {
            get {
                return ResourceManager.GetString("MainLayoutLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat výběrovníky.
        /// </summary>
        internal static string MainLayoutManageCodeLists {
            get {
                return ResourceManager.GetString("MainLayoutManageCodeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat úložiště.
        /// </summary>
        internal static string MainLayoutManageRepository {
            get {
                return ResourceManager.GetString("MainLayoutManageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat úlohy.
        /// </summary>
        internal static string MainLayoutManageTasks {
            get {
                return ResourceManager.GetString("MainLayoutManageTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat uživatele.
        /// </summary>
        internal static string MainLayoutManageUsers {
            get {
                return ResourceManager.GetString("MainLayoutManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornění.
        /// </summary>
        internal static string MainLayoutNotifications {
            get {
                return ResourceManager.GetString("MainLayoutNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        internal static string MainLayoutSettings {
            get {
                return ResourceManager.GetString("MainLayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdíleno se mnou.
        /// </summary>
        internal static string MainLayoutSharedWithMe {
            get {
                return ResourceManager.GetString("MainLayoutSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika.
        /// </summary>
        internal static string MainLayoutStatistics {
            get {
                return ResourceManager.GetString("MainLayoutStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailov8 adresa..
        /// </summary>
        internal static string RegisterFormEmailInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinné pole..
        /// </summary>
        internal static string RegisterFormEmailInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormEmailInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string RegisterFormFamilyNameInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormFamilyNameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinné pole..
        /// </summary>
        internal static string RegisterFormFamilyNameInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormFamilyNameInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string RegisterFormGivenNameInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormGivenNameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinné pole..
        /// </summary>
        internal static string RegisterFormGivenNameInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormGivenNameInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        internal static string RegisterFormLoginButton {
            get {
                return ResourceManager.GetString("RegisterFormLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string RegisterFormPasswordInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinné pole..
        /// </summary>
        internal static string RegisterFormPasswordInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormPasswordInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit heslo.
        /// </summary>
        internal static string RegisterFormPasswordInputShowPasswordAriaLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordInputShowPasswordAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opakování hesla.
        /// </summary>
        internal static string RegisterFormPasswordRepeatInputLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordRepeatInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinné pole..
        /// </summary>
        internal static string RegisterFormPasswordRepeatInputRequiredError {
            get {
                return ResourceManager.GetString("RegisterFormPasswordRepeatInputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit heslo.
        /// </summary>
        internal static string RegisterFormPasswordRepeatInputShowPasswordAriaLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordRepeatInputShowPasswordAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat se.
        /// </summary>
        internal static string RegisterFormRegisterButton {
            get {
                return ResourceManager.GetString("RegisterFormRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat se.
        /// </summary>
        internal static string RegisterFormTitle {
            get {
                return ResourceManager.GetString("RegisterFormTitle", resourceCulture);
            }
        }
    }
}
