//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSlozka.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSlozka.Web.Resources.App.cs", typeof(App_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailová adresa.
        /// </summary>
        internal static string LoginEmailInputLabel {
            get {
                return ResourceManager.GetString("LoginEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to petr.novotny@centrum.cz.
        /// </summary>
        internal static string LoginEmailInputPlaceholder {
            get {
                return ResourceManager.GetString("LoginEmailInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        internal static string LoginLoginButtonText {
            get {
                return ResourceManager.GetString("LoginLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit heslo.
        /// </summary>
        internal static string LoginPasswordInputAdornmentArialLabel {
            get {
                return ResourceManager.GetString("LoginPasswordInputAdornmentArialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string LoginPasswordInputLabel {
            get {
                return ResourceManager.GetString("LoginPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat se.
        /// </summary>
        internal static string LoginRegisterButtonText {
            get {
                return ResourceManager.GetString("LoginRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESLOZKA.
        /// </summary>
        internal static string MainLayoutAppbarBrand {
            get {
                return ResourceManager.GetString("MainLayoutAppbarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet.
        /// </summary>
        internal static string MainLayoutAppbarDrawerLinkAccount {
            get {
                return ResourceManager.GetString("MainLayoutAppbarDrawerLinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        internal static string MainLayoutAppbarDrawerLinkLogout {
            get {
                return ResourceManager.GetString("MainLayoutAppbarDrawerLinkLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        internal static string MainLayoutAppbarDrawerLinkSettings {
            get {
                return ResourceManager.GetString("MainLayoutAppbarDrawerLinkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkAboutApplication {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkAboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkAccount {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záložky.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkBookmarks {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazané.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkDeleted {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkFiles {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historie.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkHistory {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkLogout {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logy.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkLogs {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat výběrovníky.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageCodeLists {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageCodeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat úložiště.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageRepository {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageStatistics {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat úlohy.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageTasks {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat uživatele.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkManageUsers {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornění.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkNotifications {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkSettings {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdíleno se mnou.
        /// </summary>
        internal static string MainLayoutSidebarDrawerLinkSharedWithMe {
            get {
                return ResourceManager.GetString("MainLayoutSidebarDrawerLinkSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailová adresa.
        /// </summary>
        internal static string RegisterEmailInputLabel {
            get {
                return ResourceManager.GetString("RegisterEmailInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to petr.novotny@centrum.cz.
        /// </summary>
        internal static string RegisterEmailInputPlaceholder {
            get {
                return ResourceManager.GetString("RegisterEmailInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string RegisterFamilyNameInputLabel {
            get {
                return ResourceManager.GetString("RegisterFamilyNameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novotný.
        /// </summary>
        internal static string RegisterFamilyNameInputPlaceholder {
            get {
                return ResourceManager.GetString("RegisterFamilyNameInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string RegisterGivenNameInputLabel {
            get {
                return ResourceManager.GetString("RegisterGivenNameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petr.
        /// </summary>
        internal static string RegisterGivenNameInputPlaceholder {
            get {
                return ResourceManager.GetString("RegisterGivenNameInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        internal static string RegisterLoginButtonText {
            get {
                return ResourceManager.GetString("RegisterLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit heslo.
        /// </summary>
        internal static string RegisterPasswordInputAdornmentAriaLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordInputAdornmentAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string RegisterPasswordInputLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit heslo.
        /// </summary>
        internal static string RegisterPasswordRepeatInputAdornmentAriaLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordRepeatInputAdornmentAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opakování hesla.
        /// </summary>
        internal static string RegisterPasswordRepeatInputLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordRepeatInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat se.
        /// </summary>
        internal static string RegisterRegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat se.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota pole &apos;Emailová adresa&apos; je již zabraná..
        /// </summary>
        internal static string ValidationUserEmailExists {
            get {
                return ResourceManager.GetString("ValidationUserEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Emailová adresa&apos; má neplatný formát..
        /// </summary>
        internal static string ValidationUserEmailFormat {
            get {
                return ResourceManager.GetString("ValidationUserEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Emailová adresa&apos; může obsahovat nejvýše 256 znaků..
        /// </summary>
        internal static string ValidationUserEmailMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserEmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Emailová adresa&apos; je povinné..
        /// </summary>
        internal static string ValidationUserEmailRequired {
            get {
                return ResourceManager.GetString("ValidationUserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Příjmení&apos; může obsahovat nejvýše 256 znaků..
        /// </summary>
        internal static string ValidationUserFamilyNameMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserFamilyNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Příjmení&apos; je povinné..
        /// </summary>
        internal static string ValidationUserFamilyNameRequired {
            get {
                return ResourceManager.GetString("ValidationUserFamilyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Jméno&apos; může obsahovat nejvýše 256 znaků..
        /// </summary>
        internal static string ValidationUserGivenNameMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserGivenNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Jméno&apos; je povinné..
        /// </summary>
        internal static string ValidationUserGivenNameRequired {
            get {
                return ResourceManager.GetString("ValidationUserGivenNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Heslo&apos; musí obsahovat nejméně 1malé písmeno..
        /// </summary>
        internal static string ValidationUserPasswordLowerCaseCharacter {
            get {
                return ResourceManager.GetString("ValidationUserPasswordLowerCaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Heslo&apos; může obsahovat nejvýše 256 znaků..
        /// </summary>
        internal static string ValidationUserPasswordMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Heslo&apos; může obsahovat nejméně 8 znaků..
        /// </summary>
        internal static string ValidationUserPasswordMinLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Heslo&apos; musí obsahovat nejméně 1 číselný znak..
        /// </summary>
        internal static string ValidationUserPasswordNumericCharacter {
            get {
                return ResourceManager.GetString("ValidationUserPasswordNumericCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Heslo&apos; musí být shodné s polem &apos;Opakování hesla&apos;..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionMatch {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Opakování hesla&apos; může obsahovat nejvýše 256 znaků..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionMaxLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Opakování hesla&apos; může obsahovat nejvýše 256 znaků..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionMinLength {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Heslo&apos; je povinné..
        /// </summary>
        internal static string ValidationUserPasswordRepetitionRequired {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRepetitionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Opakování hesla&apos; je povinné..
        /// </summary>
        internal static string ValidationUserPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationUserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Heslo&apos; musí obsahovat nejméně speciální znak..
        /// </summary>
        internal static string ValidationUserPasswordSpecialCharacter {
            get {
                return ResourceManager.GetString("ValidationUserPasswordSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Heslo&apos; musí obsahovat nejméně velké písmeno..
        /// </summary>
        internal static string ValidationUserPasswordUpperCaseCharacter {
            get {
                return ResourceManager.GetString("ValidationUserPasswordUpperCaseCharacter", resourceCulture);
            }
        }
    }
}
